version: '2'

services:
    consul:
        image: bhuisgen/rpi-alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    kivy:
        depends_on:
            - consul
        image: bhuisgen/rpi-alpine-kivy
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
        devices:
            - /dev/vchiq
        environment:
            - CONSUL_AGENT=consul                  # consul agent hostname/IP
            #- CONSUL_PORT=8500                    # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/       # consul key prefix path
            - HOSTAPD_INTERFACE=wlx74da386015cd    # AP interface
            - HOSTAPD_SSID=${USERNAME}             # AP network SSID
            - HOSTAPD_COUNTRYCODE=FR               # AP country code
            - HOSTAPD_WPAPASSPHRASE=1234567890     # AP WPA passphrase
